apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: my-web-app
  ports:
    - protocol: TCP
      port: 8080      # The port that the Service listens on inside the cluster
      targetPort: 80  # The port inside the Pod container where traffic is sent
