name: Testing Context Variables

on:
  workflow_dispatch

env:
  cloud: google-cloud

jobs:
  test_context_variables:
    runs-on: git-hub-actiondemo
    steps:
      - name: "Checking Context Variable"
        run: |
          echo "Repository Name : ${{ github.repository }}"
          echo "Workflow Name : ${{ github.workflow }}"
          echo "Triggered by : ${{ github.triggering_actor }}"
          echo "deploy-${{ github.ref }}"
          echo "Owner - ${{ github.repository_owner }}"
          echo "Actor - ${{ github.actor }}"
